title: Ty Modding Wiki
description: A wiki for all info about Ty modding
theme: just-the-docs

url: https://tymoddingwiki.github.io

aux_links:
  Template Repository: https://github.com/TyModdingWiki/tymoddingwiki
