site_name: Ty Modding Wiki
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: blue
      accent: amber
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference
      primary: indigo
      accent: amber
  logo_light_mode: assets/GoldCogIcon.png
  logo_dark_mode: assets/PlatinumCogIcon.png
  favicon: assets/GoldCogIcon.png

extra_css:
  - css/LogoToggle.css

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/g8kHTR42Cc

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.betterem
  - admonition
  - attr_list